import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    cart: [],
    cartTotalPrice: 0,
    itemsInCart: 0,
    showPopup: false,
    productsData:[
      {
        sku: 1,
        star: true,
        psu: true,
        name: 'USED Antminer S9',
        property: '10.5-14.5 th/s',
        image: require('../assets/img/item1.png'),
        price: 137.00,
        quantity: 0,
      },
      {
        sku: 2,
        star: false,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item2.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 3,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item3.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 4,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item4.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 5,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item5.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 6,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item6.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 7,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item7.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 8,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item8.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 1,
        star: true,
        psu: true,
        name: 'USED Antminer S9',
        property: '10.5-14.5 th/s',
        image: require('../assets/img/item1.png'),
        price: 137.00,
        quantity: 0,
      },
      {
        sku: 2,
        star: false,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item2.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 3,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item3.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 4,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item4.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 5,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item5.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 6,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item6.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 7,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item7.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 8,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item8.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 1,
        star: true,
        psu: true,
        name: 'USED Antminer S9',
        property: '10.5-14.5 th/s',
        image: require('../assets/img/item1.png'),
        price: 137.00,
        quantity: 0,
      },
      {
        sku: 2,
        star: false,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item2.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 3,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item3.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 4,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item4.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 5,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item5.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 6,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item6.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 7,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item7.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 8,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item8.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 1,
        star: true,
        psu: true,
        name: 'USED Antminer S9',
        property: '10.5-14.5 th/s',
        image: require('../assets/img/item1.png'),
        price: 137.00,
        quantity: 0,
      },
      {
        sku: 2,
        star: false,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item2.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 3,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item3.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 4,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item4.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 5,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item5.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 6,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item6.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 7,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item7.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 8,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item8.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 1,
        star: true,
        psu: true,
        name: 'USED Antminer S9',
        property: '10.5-14.5 th/s',
        image: require('../assets/img/item1.png'),
        price: 137.00,
        quantity: 0,
      },
      {
        sku: 2,
        star: false,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item2.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 3,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item3.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 4,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item4.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 5,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item5.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 6,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item6.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 7,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item7.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 8,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item8.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 1,
        star: true,
        psu: true,
        name: 'USED Antminer S9',
        property: '10.5-14.5 th/s',
        image: require('../assets/img/item1.png'),
        price: 137.00,
        quantity: 0,
      },
      {
        sku: 2,
        star: false,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item2.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 3,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item3.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 4,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item4.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 5,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item5.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 6,
        star: true,
        psu: false,
        name: 'Antminer DR5',
        property: '35 Th/s',
        image: require('../assets/img/item6.png'),
        price: 1580.00,
        quantity: 0,
      },
      {
        sku: 7,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item7.png'),
        price: 1385.00,
        quantity: 0,
      },
      {
        sku: 8,
        star: false,
        psu: true,
        name: 'PandaMiner B3 Pro 4g',
        property: '230 Mh/s',
        image: require('../assets/img/item8.png'),
        price: 1385.00,
        quantity: 0,
      },
    ]
  },
  mutations: {
    setTotalPrice(state, price){
      state.cartTotalPrice = price;
    },
    clearCart(state){
      state.cart = [];
    },
    setItemsInCart(state){
      let items = 0;
      for( let  i of state.cart){
        items= items + i.quantity;
      }
      state.itemsInCart = items;
    },
    setIsShowPopup(state){
      state.showPopup = !state.showPopup;
    }
  },
  actions: {
  },
  modules: {
  }
})
